# Generated by Django 5.0.6 on 2024-07-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
