# Generated by Django 5.0.6 on 2024-07-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_paymentmethod_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaPaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumer_key", models.CharField(max_length=100)),
                ("consumer_secret", models.CharField(max_length=100)),
                ("pass_key", models.CharField(max_length=100)),
                ("short_code", models.CharField(max_length=100)),
                ("test_mode", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Mpesa Payment Settings",
                "verbose_name_plural": "Mpesa Payment Settings",
            },
        ),
    ]
