# Generated by Django 5.0.6 on 2024-07-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_mpesapaymentsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("In progress", "In progress"),
                    ("Complete", "Complete"),
                    ("Cancelled", "Cancelled"),
                ],
                default="In progress",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
