# Generated by Django 5.0.6 on 2024-07-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payment_notes_payment_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("In progress", "In progress"),
                    ("Complete", "Complete"),
                    ("Cancelled", "Cancelled"),
                    ("Pending", "Pending"),
                ],
                default="In progress",
                max_length=30,
            ),
        ),
    ]
