# Generated by Django 5.0.6 on 2024-07-21 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0010_tenant_tenant_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notice_date", models.DateTimeField(auto_now_add=True)),
                ("vacation_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacation_notices",
                        to="tenants.lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacation Notice",
                "verbose_name_plural": "Vacation Notices",
                "ordering": ["-notice_date"],
            },
        ),
    ]
