# Generated by Django 5.0.6 on 2024-07-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={
                "ordering": ["name"],
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
            },
        ),
        migrations.RemoveField(
            model_name="agent",
            name="user",
        ),
        migrations.AddField(
            model_name="agent",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="agents/"),
        ),
        migrations.AddField(
            model_name="agent",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
