# Generated by Django 5.0.6 on 2024-07-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_agent_options_remove_agent_user_agent_email_and_more"),
        ("properties", "0009_remove_house_amenities_delete_amenity"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="properties",
            field=models.ManyToManyField(to="properties.property"),
        ),
    ]
