# Generated by Django 5.0.6 on 2024-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_remove_lease_rent_amount_alter_lease_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
