# Generated by Django 5.0.6 on 2024-07-05 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_lease_deposit_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="user",
        ),
        migrations.AddField(
            model_name="lease",
            name="renew_monthly",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="first_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="last_name",
            field=models.CharField(default="Name", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone_number",
            field=models.CharField(default="0712345678", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="tenants/"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
