# Generated by Django 5.0.6 on 2024-07-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_remove_tenant_user_lease_renew_monthly_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-payment_date"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
