# Generated by Django 5.0.6 on 2024-07-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_remove_house_amenities_delete_amenity"),
        ("tenants", "0005_alter_payment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="houses",
            field=models.ManyToManyField(to="properties.house", verbose_name="houses"),
        ),
    ]
