# Generated by Django 5.0.6 on 2024-07-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_tenant_houses"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
