# Generated by Django 5.0.6 on 2024-07-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_alter_house_rent"),
        ("tenants", "0007_delete_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="houses",
            field=models.ManyToManyField(
                blank=True, null=True, to="properties.house", verbose_name="houses"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
