# Generated by Django 5.0.6 on 2024-07-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_alter_house_rent"),
        ("tenants", "0008_alter_tenant_houses_alter_tenant_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="houses",
            field=models.ManyToManyField(
                blank=True, to="properties.house", verbose_name="houses"
            ),
        ),
    ]
