# Generated by Django 5.0.6 on 2024-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_alter_tenant_houses"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="tenant_type",
            field=models.CharField(
                choices=[("Business", "Business"), ("Individual", "Individual")],
                default="Individual",
                max_length=255,
            ),
        ),
    ]
