# Generated by Django 5.0.6 on 2024-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_property_purpose"),
        ("tenants", "0010_tenant_tenant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="houses",
            field=models.ManyToManyField(
                blank=True, null=True, to="properties.house", verbose_name="houses"
            ),
        ),
    ]
