# Generated by Django 5.0.6 on 2024-07-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_alter_tenant_houses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="lease",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
