# Generated by Django 5.0.6 on 2024-07-28 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0013_alter_lease_end_date_alter_lease_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leases",
                to="tenants.tenant",
            ),
        ),
    ]
