# Generated by Django 5.0.6 on 2024-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_alter_lease_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="is_paid_completely",
            field=models.BooleanField(default=False),
        ),
    ]
