# Generated by Django 5.0.6 on 2024-07-05 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlords", "0001_initial"),
        ("properties", "0008_remove_property_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyCareTaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_care_takers/"
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caretakers",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Care Taker",
                "verbose_name_plural": "Property Care Takers",
            },
        ),
        migrations.DeleteModel(
            name="Landlord",
        ),
    ]
