# Generated by Django 5.0.6 on 2024-07-05 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlords", "0002_propertycaretaker_delete_landlord"),
        ("properties", "0008_remove_property_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertycaretaker",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="propertycaretaker",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="propertycaretaker",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caretakers",
                to="properties.property",
            ),
        ),
    ]
