# Generated by Django 5.0.6 on 2024-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("description", models.CharField(default="", max_length=300)),
                ("number", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.AddField(
            model_name="house",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="amenities", to="properties.amenity"
            ),
        ),
    ]
