# Generated by Django 5.0.6 on 2024-06-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_amenity_house_amenities"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[("RESIDENTIAL", "Residential"), ("COMMERCIAL", "Commercial")],
                default="RESIDENTIAL",
                max_length=30,
                null=True,
            ),
        ),
    ]
