# Generated by Django 5.0.6 on 2024-06-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_agemt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='agemt',
            new_name='agent',
        ),
    ]
