# Generated by Django 5.0.6 on 2024-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_house_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RESIDENTIAL", "Residential"),
                    ("COMMERCIAL", "Commercial"),
                    ("OTHER", "Other"),
                ],
                default="RESIDENTIAL",
                max_length=30,
                null=True,
            ),
        ),
    ]
