# Generated by Django 5.0.6 on 2024-06-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_house_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="description",
            field=models.TextField(
                blank=True, default="No additional description", null=True
            ),
        ),
    ]
