# Generated by Django 5.0.6 on 2024-06-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_house_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="landlord",
        ),
    ]
