# Generated by Django 5.0.6 on 2024-06-30 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_remove_property_landlord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=50)),
                ("floor", models.CharField(max_length=30)),
                ("houses", models.ManyToManyField(to="properties.house")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Unit",
                "verbose_name_plural": "Property Units",
            },
        ),
    ]
