# Generated by Django 5.0.6 on 2024-07-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="agent",
        ),
    ]
