# Generated by Django 5.0.6 on 2024-07-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_remove_property_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="amenities",
        ),
        migrations.DeleteModel(
            name="Amenity",
        ),
    ]
