# Generated by Django 5.0.6 on 2024-07-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_remove_house_amenities_delete_amenity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="number_of_rooms",
            field=models.IntegerField(default=1),
        ),
    ]
