# Generated by Django 5.0.6 on 2024-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_alter_house_number_of_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="rent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
