# Generated by Django 5.0.6 on 2024-07-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_alter_house_rent"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RESIDENTIAL", "Residential"),
                    ("COMMERCIAL", "Commercial"),
                    ("OTHER", "Other"),
                ],
                default="RESIDENTIAL",
                max_length=30,
                null=True,
            ),
        ),
    ]
