# Generated by Django 5.0.6 on 2024-07-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_property_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="units", to="properties.entityphoto"
            ),
        ),
    ]
