# Generated by Django 5.0.6 on 2024-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
