# Generated by Django 5.0.6 on 2024-07-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_alter_message_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="subject",
        ),
    ]
