# Generated by Django 5.0.6 on 2024-07-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0003_remove_message_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="Notification", max_length=100),
        ),
    ]
