# Generated by Django 5.0.6 on 2024-06-26 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="property",
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.house",
            ),
        ),
    ]
