# Generated by Django 5.0.6 on 2024-07-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_remove_maintenancerequest_property_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="requested_by",
        ),
    ]
