# Generated by Django 5.0.6 on 2024-07-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_remove_maintenancerequest_requested_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintainer_type",
                    models.CharField(
                        choices=[("Individual", "Individual"), ("Company", "Company")],
                        default="Individual",
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Maintainer",
                "verbose_name_plural": "Maintainers",
            },
        ),
    ]
