# Generated by Django 5.0.6 on 2024-07-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0005_maintenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Complete", "Complete"),
                    ("Scheduled", "Scheduled"),
                    ("Complete", "Complete"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
