# Generated by Django 5.0.6 on 2024-07-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0006_maintenancerequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="completed_date",
        ),
    ]
