# Generated by Django 5.0.6 on 2024-07-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0007_remove_maintenancerequest_completed_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Progress", "In Progress"),
                    ("Scheduled", "Scheduled"),
                    ("Pending", "Pending"),
                    ("Complete", "Complete"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
