# Generated by Django 5.0.6 on 2024-08-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0008_alter_maintenancerequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
