# Generated by Django 5.0.6 on 2024-07-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="currency",
            field=models.CharField(default="KES", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="language",
            field=models.CharField(default="en", max_length=100),
        ),
    ]
