# Generated by Django 5.0.6 on 2024-07-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_company_currency_company_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField()),
                ("smtp_server", models.CharField(max_length=30)),
                ("use_tls", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=30)),
                ("name", models.CharField(default="default server", max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mail Settings",
                "verbose_name_plural": "Mail Settings",
            },
        ),
    ]
